# Site settings
title: "Jacqui and Ben's Wedding"
description: Space Otter and Bhuga get married

# Files
baseurl:
pagesdir: pages
assets:
  libs: assets/libs
  owner: assets/owner
logo: logo.png
discus_shortname: Jacqui and Ben's Wedding
email: jacqnelson@gmail.com
url: "http://spaceotterinspace.com/spaceotterandbhuga"
search: true
share: true
comments: true
future: true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: true

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200

# Owner/author information
owner:
  name:   Jacqui and Ben's Wedding
  avatar: avatar.jpg
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Space Otter and Bhuga get married

# Social networking links used in footer. Update and remove as you like.
twitter_username: spaceotterin
github_username: spaceotterinspace

# Internal nav
nav:
 events: "root_url/events/"
 registry: "root_url/registry/"
 accommodations: "root_url/accommodations/"


# Server
destination:      	 ./_site
port:             	 4000


#dependencies
# Gems
gems:
  - jekyll-paginate


# Build settings
highlighter:         rouge
markdown:           kramdown
kramdown:
    extensions:     
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
sass:
    style:          :compressed
paginate: 5
paginate_path: "/events/page:num/"
permalink: "/events/:title/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"


# Analytics and webmaster tools stuff goes here
google_analytics:   UA-xxxxxxxx-x
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         
